#!/usr/bin/env python3

import yaml
cred = yaml.load(open("credentials.yml"))['email']

server = cred['server']
user = cred['id']
pwd = cred['secret']

import sys
import smtplib
import email.message

try:
	from_ = cred['from']
	to = sys.argv[1]
	subject = sys.argv[2]
	body = sys.argv[3] #TODO: support mail(1)-style read-from-stdin thing
except IndexError:
	usage()
except KeyError:
	print("You must configure account settings in credentials.yml", file=sys.stderr)

msg = email.message.Message()
msg['From'] = from_
msg['To'] = to
msg['Subject'] = subject
msg.set_payload(body)

starttls = cred.get('starttls',False)
#weird: with my server (comms.kousu.ca) I have to use smtps or else it rejects my auth
# but gmail works fine. So I've added a switch.
if starttls:
	smtp = smtplib.SMTP(server,587)
	print(smtp.ehlo())
	print(smtp.starttls()) #Dont need this becasue we're already SSL'd
	# Notice: after starttls you must re-hello because your permissions ("smtp Capabilities") can change
else:
	smtp = smtplib.SMTP_SSL(server)
print(smtp.ehlo())
print(smtp.login(user, pwd))


smtp.send_message(msg)
smtp.close()
